codestates-seb/seb45_main_022

.github/ISSUE_TEMPLATE/issue-task-card.md
README.md
Server/src/main/java/com/codestatus/advice/GlobalExceptionAdvice.java
Server/src/main/java/com/codestatus/response/ErrorResponse.java
Server/src/main/java/com/codestatus/response/ValidationErrorResponse.java

✨ feat: error response handler 추가

---

Server/src/main/java/com/codestatus/auth/config/SecurityConfig.java
Server/src/main/java/com/codestatus/feed/controller/FeedController.java
Server/src/main/java/com/codestatus/feed/entity/Feed.java
Server/src/main/java/com/codestatus/feed/service/FeedService.java
Server/src/main/java/com/codestatus/like/entity/Like.java
Server/src/main/java/com/codestatus/user/controller/UserController.java
Server/src/main/java/com/codestatus/user/service/UserService.java

✨ feat: 유저 탈퇴 기능 추가

---

Server/src/main/java/com/codestatus/domain/comment/controller/CommentController.java
Server/src/main/java/com/codestatus/domain/comment/service/CommentService.java

♻ refactor:comment 도메인 refactoring
- 기존 comment service를 BaseService를 구현하도록 수정하였습니다.
- comment service에서 사용하던 mapper를 controller에서 사용하도록 수정하였습니다.
Test Case
- comment CUD 기능 다 테스트 완료하였습니다.

♻ refactor:comment 도메인 refactoring

---

Client/src/components/user/Login.tsx
Client/src/components/user/Register.tsx

회원가입 'Login' 버튼 수정 및 로그인 페이지에서 hover 효과 추가

🐛 fix: 회원가입 페이지에서 로그인 페이지 이동 버튼 수정

---

Client/package-lock.json
Client/package.json
Client/public/user/test.json
Client/src/components/title/StatusChart.tsx
Client/src/components/title/StatusListItem.tsx
Client/src/components/title/StatusScreen.tsx

- 스테이터스 차트
- 스테이터스 리스트
- 스테이터스 리스트 아이템 클릭 시, 해당 스테이터스의 카테고리 선택 페이지로 이동

✨ feat: 스테이터스 창

---

Server/src/main/java/com/codestatus/domain/image/controller/ImageController.java
Server/src/main/java/com/codestatus/domain/image/dto/ImageResponseDto.java
Server/src/main/java/com/codestatus/domain/image/mapper/ImageMapper.java
Server/src/main/java/com/codestatus/domain/image/service/ImageService.java
Server/src/main/java/com/codestatus/domain/user/service/UserService.java

✨ feat: feed 이미지 업로드용 image url 반환 api 추가

✨ feat: feed 이미지 업로드용 image url 반환 api 추가

---

Client/package-lock.json
Client/package.json
Client/public/user/users.json
Client/src/components/title/LoginSection.tsx
Client/src/main.tsx
Client/src/redux/actions/actions.js
Client/src/redux/reducers/reducer.js
Client/src/redux/store/store.js

React Query 설치하시고 사용할때 useMutation와 useQuery 차이점 알고 있으면 좋을 것 같습니다. 
useMutation:  Server State를 변경시키는 hook (create, update, delete) - POST, PATCH
useQuery: Server State를 읽어오는 hook (read) (GET이랑 비슷한 개념) 
****
- React query 설치했습니다. 
- Pull하시고 npm install 실행해주세요
- main.tsx 수정 내용 입니다. 
- ReactQueryDevtools는 상태관리 툴입니다. 페이지 왼쪽 하단 아이콘 클릭하여 확인할 수 있습니다. 
****

✨ feat: 사용자 로그인 창  

---

Server/src/main/java/com/codestatus/domain/like/repository/LikeRepository.java
Server/src/main/java/com/codestatus/domain/like/service/LikeService.java
Server/src/main/java/com/codestatus/domain/user/service/UserService.java
Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java
Server/src/main/resources/application-server.yml

✨ feat: gain exp when first like
- UserService에 User 객체, 얻는 exp 량, statId를 받아 
statExp를 증가시키는 메서드를 추가하였습니다.
- exp 증가 직후 levelUpCheck 메서드를 실행하도록 하였습니다.
- 출석 경험치, 좋아요 경험치 @Value 사용해서 field로 추가하였습니다.
Test Case
- postman 활용해 첫 좋아요 시 피드 주인의 스탯 경험치가 오르는 걸 확인했고,
좋아요 취소, 재좋아요도 확인하였습니다.

✨ feat: gain exp when first like

---

Client/src/api/auth.ts
Client/src/components/title/LoginSection.tsx
Client/src/components/title/RegisterSection.tsx
Client/src/hooks/validation.ts

- api 폴더 생성 (로그인 및 회원가입 api 호출 분리작업) 
- validation.ts 훅 파일 생성 (유효성 검사) 
- LoginSection.tsx rebase하고 수정내용 반영 (충돌 막기위해) 
- 유효성 검사 수정 (onBlur 함수 추가)

✨ feat: 회원가입 페이지 유효성 검사 수정 및 refactoring 

---

Server/build.gradle
Server/src/main/java/com/codestatus/global/mail/controller/EmailController.java
Server/src/main/java/com/codestatus/global/mail/dto/EmailDto.java
Server/src/main/java/com/codestatus/global/mail/entity/Email.java
Server/src/main/java/com/codestatus/global/mail/mapper/EmailMapper.java
Server/src/main/java/com/codestatus/global/mail/service/EmailService.java
Server/src/main/resources/application-server.yml

1. JavaMailSender 사용을 위한 기본 설정 추가
- application-server.yml -> 이메일 발송 관련 설정 추가(gmail smtp 사용)
- build.gradle -> 이메일 의존성 추가
2. 가입시 이메일 인증에 필요한 코드 생성 및 이메일 발송 api 추가

✨ feat: 이메일 발송 기능 추가

---

Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
Server/src/main/java/com/codestatus/domain/hashTag/mapper/HashTagMapper.java

♻️ refactor: 의미 없는 코드 삭제, +@RequiredArgsConstructor

---

Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagService.java
Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagServiceImpl.java

✨ feat: 검색기능, 카테고리 별 리스트 조회 추가
♻️ refactor: feedController역할에 맞게 서비스로 분리하여 리팩토링.

✨ feat, ♻️ refactor: feed

---

Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
Server/src/main/java/com/codestatus/domain/feed/dto/FeedsResponseDto.java
Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
Server/src/main/java/com/codestatus/domain/hashTag/dto/HashTagResponseDto.java
Server/src/main/java/com/codestatus/domain/hashTag/entity/FeedHashTag.java
Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagService.java

♻️ refactor: 고군분투의 흔적 삭제

---

Server/src/main/java/com/codestatus/domain/user/repository/UserRepository.java

- userRepository 에 쿼리문 작성
- 동작 테스트 완료

📝 docs: UserRepository 쿼리문 추가

---

Server/src/main/java/com/codestatus/global/auth/config/SecurityConfig.java

- SecurityConfig 내 feed api 권한부여
- 전체 조회, 주간베스트, 피드 검색 전체 허용 
- 피드 작성, 상세 조회, 수정, 삭제는 USER 권한 필요

✨ feat: feed api 권한부여

---

Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java
Server/src/main/java/com/codestatus/global/utils/ExpTableGenerator.java

🐛 fix: 유저 status 생성시 필요경험치 기본값 100으로 설정
🐛 fix: FeedController api 중 카테고리 id 를 사용하는 api 에 1~13 범위의 수만 허용하게 설정

🐛 fix: status 생성 및 feed api 일부 수정

---

Server/src/main/java/com/codestatus/global/auth/config/SecurityConfig.java
Server/src/main/java/com/codestatus/global/auth/filter/JwtAuthenticationFilter.java
Server/src/main/java/com/codestatus/global/auth/filter/JwtVerificationFilter.java
Server/src/main/java/com/codestatus/global/auth/handler/OAuth2UserSuccessHandler.java
Server/src/main/java/com/codestatus/global/auth/provider/CustomAuthenticationProvider.java
Server/src/main/java/com/codestatus/global/auth/userdetails/UsersDetailService.java
Server/src/main/java/com/codestatus/global/auth/utils/JwtResponseUtil.java

✨ feat:custom authentication provider 추가
- authentication으로 회원 상태를 조회하여 그에 따라 로그인을 진행하는 기능을 추가하였습니다.
♻ refactor:RequiredArgsContsructor 적용
- global/auth 패키지 내에 RequiredArgsContsructor를 적용하였습니다.
Test Case:
postman으로 로그인 상태가 ACTIVE가 아닌 유저로 로그인을 해봤습니다.

✨ feat:custom authentication provider 추가 및 ♻ refactor:RequiredArgsContsructor적용

---

Server/src/main/java/com/codestatus/domain/feed/dto/FeedPatchDto.java
Server/src/main/java/com/codestatus/domain/feed/dto/FeedPostDto.java
Server/src/main/java/com/codestatus/domain/feed/dto/FeedResponseDto.java
Server/src/main/java/com/codestatus/domain/feed/dto/FeedsResponseDto.java
Server/src/main/java/com/codestatus/domain/feed/entity/Feed.java
Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java

- feed table에 data 컬럼 추가
- feed 작성시 data 컬럼에 editor json 저장
- feed 작성시 body 컬럼에 검색용 문자열 저장
- feed 조회시 data 컬럼 응답
- feed 수정시 data 컬럼도 수정되게 추가
- feed 본문 검색 쿼리 수정
- 변경내용 테스트 완료

♻️ refactor: feed 작성, 검색, 수정 변경

---

Client/src/components/map/ServerList.tsx
Client/src/hooks/useFeedList.tsx
Client/src/pages/FeedPage.tsx
Client/src/pages/MapPage.tsx

- React Query를 사용하여 피드 페이지 코드를 리팩토링 완료하였습니다.

♻️ refactor: React query를 사용한 커스텀 훅으로 피드 조회 리팩토링

---

Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
Server/src/main/java/com/codestatus/domain/feed/dto/FeedPostDto.java
Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
Server/src/main/java/com/codestatus/domain/image/controller/ImageController.java
Server/src/main/java/com/codestatus/domain/image/service/ImageService.java
Server/src/main/java/com/codestatus/domain/user/controller/UserController.java
Server/src/main/java/com/codestatus/domain/user/dto/UserDto.java
Server/src/main/java/com/codestatus/domain/user/entity/User.java
Server/src/main/java/com/codestatus/domain/user/mapper/UserMapper.java
Server/src/main/java/com/codestatus/domain/user/repository/UserRepository.java
Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java
Server/src/main/java/com/codestatus/global/report/service/ReportFeedServiceImpl.java

- 주간베스트 조회시 카테고리별로 조회되게 수정
- 주간베스트 조회시 likes 의 사이즈로 정렬하게 쿼리 수정
- 현재 주간베스트 조회시 likes 의 사이즈를 1순위로 정렬하고 likes의 사이즈가 같거나 0인 피드는 최신순으로 정렬 됩니다.
- 일부 미사용 메서드, import 삭제
- User Entity 필드 중 nickName 을 nickname 으로 변경
- 메서드명에 nickName 을 nickname 으로 변경

🐛 fix: 주간베스트 수정

---

Server/src/main/java/com/codestatus/domain/attendance/service/AttendanceService.java
Server/src/main/java/com/codestatus/domain/comment/command/CommentCommand.java
Server/src/main/java/com/codestatus/domain/comment/service/CommentServiceImpl.java
Server/src/main/java/com/codestatus/domain/feed/command/FeedCommand.java
Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
Server/src/main/java/com/codestatus/domain/feed/service/FeedService.java
Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
Server/src/main/java/com/codestatus/domain/hashTag/command/FeedHashTagCommand.java
Server/src/main/java/com/codestatus/domain/hashTag/repository/FeedHashTagRepository.java
Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagService.java
Server/src/main/java/com/codestatus/domain/hashTag/service/HashTagServiceImpl.java
Server/src/main/java/com/codestatus/domain/like/service/LikeService.java
Server/src/main/java/com/codestatus/domain/user/command/LevelCommand.java
Server/src/main/java/com/codestatus/domain/user/command/UserCommand.java
Server/src/main/java/com/codestatus/domain/user/service/LevelService.java
Server/src/main/java/com/codestatus/domain/user/service/UserService.java
Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java
Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java
Server/src/main/java/com/codestatus/global/report/service/ReportFeedServiceImpl.java

♻ refactor:공통 기능 command화
- 공통적으로 사용하는 기능이나, 다른 도메인의 서비스를 사용하는 것을 방지하고자 
각 도메인 별로 필요한 command를 생성하고 사용하였습니다.
Test Case:
- 회원가입, 로그인, 피드 작성, 삭제, 댓글 작성, 수정, 삭제 확인했습니다.

♻ refactor:공통 기능 command화

---

Server/src/main/java/com/codestatus/domain/attendance/controller/AttendanceController.java
Server/src/main/java/com/codestatus/domain/attendance/dto/AttendanceDto.java
Server/src/main/java/com/codestatus/domain/attendance/mapper/AttendanceMapper.java
Server/src/main/java/com/codestatus/domain/attendance/repository/AttendanceRepository.java
Server/src/main/java/com/codestatus/domain/attendance/service/AttendanceService.java
Server/src/main/java/com/codestatus/domain/user/dto/UserDto.java
Server/src/main/java/com/codestatus/domain/user/entity/User.java
Server/src/main/java/com/codestatus/domain/user/mapper/UserMapper.java
Server/src/main/java/com/codestatus/global/auth/config/SecurityConfig.java
Server/src/main/resources/application-local.yml

- 출석체크 여부를 boolean 으로 반환하는 api 추가
- 출석체크 권한 부여
- application.yml show-sql 설정 false로 변경
- application-local.yml 추가 (show-sql 설정 true)
- 추가된 api 동작 테스트 완료

✨ feat: 출석체크 여부 반환 api 추가

---

Client/src/api/user.ts
Client/src/components/common/Button.tsx
Client/src/components/main/ChangePwTab.tsx
Client/src/components/main/ProfileScreen.tsx
Client/src/utility/axios.ts

- **axios** 커스텀 인스턴스 작성
- `baseURL`은 여러분 `.env`에 있는 `VITE_APP_BASE_URL` 
- 헤더에 자동으로 `Authorization: token` 담아 보냄
- 유저 정보 조회 함수에서 실제 API URL 사용
- 비밀번호 변경 기능 구현

✨ feat: 비밀번호 변경 + @

---

Client/src/api/feed.ts
Client/src/components/feed/BestFeedItem.tsx
Client/src/components/feed/FeedItem.tsx
Client/src/components/feed/LatestFeedItem.tsx
Client/src/components/feed/Main.tsx
Client/src/hooks/useFeedList.tsx
Client/src/hooks/useUserFeed.tsx
Client/src/pages/FeedPage.tsx
Client/tailwind.config.js

- 서버에서 추가된 주간 베스트 API  추가
- 최신순 및 주간 베스트 피드 분리 (기존 통합 FeedItem에서 최신순 Feed, 주간 베스트 Feed 생성) (탭 클릭 시, 페이지 렌더링)
- 상세 피드 조회 Custom Hook 및 API 분리 (게시글 클릭 시, 조회 작업 진행 예정) 
- 주간 베스트는 좋아요 순 및 게시글 업로드 순으로 정렬
####

✨ 전체 피드 조회 (최신순, 주간 베스트)

---

Client/src/api/user.ts
Client/src/components/common/ImageUploadModal.tsx
Client/src/components/main/ProfileHeader.tsx
Client/src/components/main/ProfileScreen.tsx

✨ feat: 닉네임 변경

---

Client/src/api/post.ts
Client/src/components/feed/Main.tsx
Client/src/components/feed/PostScreen.tsx
Client/src/hooks/usePost.tsx

https://github.com/codestates-seb/seb45_main_022/assets/85780501/a4b869d3-45f7-48b2-ba35-a6738ae112a7
<br>
- post.ts를 만들어서 API POST 요청을 다뤘습니다.
- usePost 훅을 만들어서 리액트 쿼리useMutation을 다뤘습니다.
- 글 작성 성공 시, 해당 카테고리 페이지로 리다이렉션 및 `feedList`만 fresh 상태 즉, refetch로 업데이트되게 하였습니다.

✨ feat: 리액트 쿼리 useMutation을 이용하여 피드 작성 기능 구현

---

Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
Server/src/main/java/com/codestatus/global/auth/config/SecurityConfig.java

- 로그인한 유저가 작성한 feed 를 조회하는 api 추가했습니다.

✨ feat: my-post api 추가

---

Server/src/main/java/com/codestatus/domain/comment/dto/CommentPostDto.java
Server/src/main/java/com/codestatus/domain/user/dto/UserDto.java
Server/src/main/java/com/codestatus/domain/user/mapper/UserMapper.java
Server/src/main/java/com/codestatus/global/advice/GlobalExceptionAdvice.java
Server/src/main/java/com/codestatus/global/auth/handler/UserAuthenticationFailureHandler.java
Server/src/main/java/com/codestatus/global/auth/utils/ErrorResponseSender.java
Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java
Server/src/main/java/com/codestatus/global/response/ErrorResponse.java
Server/src/main/java/com/codestatus/global/response/ValidationErrorResponse.java

✨ feat: add errorCode in error response
- 모든 도메인 로직에서 에러 발생 시 status code, message 외에 error code를 함께 보냅니다.
🐛fix: add NoArgsConstructor in Comment post Dto
- dto에 field가 한 개일 때 mapping이 안되는 오류를 해결했습니다.

✨ feat: add errorCode in error response, 🐛fix: add NoArgsConstructor in Comment post Dto

---

Client/src/hooks/useUserInfo.tsx
Client/src/main.tsx
Client/src/pages/PrivateRoute.tsx

없는 라우트로 접근 시 타이틀 페이지로 이동,
로그인 되지 않은 상태에서 타이틀 페이지, 로그인 / 회원가입 페이지를 제외한 페이지에 접근할 경우 로그인 페이지로 이동

✨ feat: Private route, No match route

---

Client/src/api/comment.ts
Client/src/components/feed/LatestFeedItem.tsx
Client/src/components/post/Comments.tsx
Client/src/components/post/UserPost.tsx
Client/src/hooks/useComment.tsx

- 깨지는 UI 전부 수정
- 댓글 기능 추가 (api 폴더 및 hooks 폴더에 파일 생성). 현재 새로고침 안하면 댓글 렌더링이 안되고 있습니다. FeedPage에서 추가 작업이 필요해서 PR 올리고 수정해보겠습니다. 
- 댓글 수가 3개 이상인 경우, slice로 숨겨서, '더 보기' 및 '숨기기' 버튼 추가'

✨feat : 상세 피드 디자인 변경, 댓글 추가 기능 

---

Server/Dockerfile
Server/src/main/java/com/codestatus/CodeStateMainProjectApplication.java

- 서버 시간 타임존 설정 추가
- dockerfile 타임존 설정 추가

🐛 fix: 타임존 설정 추가

---

Client/src/hooks/usePostFeedMutation.tsx

🐛 fix: 피드 작성 시 피드 조회 페이지 피드 리스트 즉시 업데이트 하도록 수정

---

Client/src/api/comment.ts
Client/src/api/editFeed.ts
Client/src/components/post/Comments.tsx
Client/src/components/post/UserPost.tsx
Client/src/hooks/useComment.tsx

✨feat: 상세 페이지 댓글 수정 및 삭제 기능, 상세 페이지 내용 수정 및 삭제

---

Client/src/api/feed.ts
Client/src/components/feed-detail/CommentSection.tsx
Client/src/components/feed-detail/FeedContentEditSection.tsx
Client/src/components/feed-detail/FeedContentSection.tsx
Client/src/components/feed-detail/FeedDetailModal.tsx
Client/src/components/feed/FeedEditor.css
Client/src/components/feed/FeedEditor.tsx
Client/src/components/feed/FeedItem.tsx
Client/src/components/feed/FeedList.tsx
Client/src/components/feed/PostScreen.tsx
Client/src/components/feed/SearchResult.tsx
Client/src/components/feed/TagEditor.tsx
Client/src/hooks/usePatchFeedMutation.tsx
Client/src/main.tsx

✨ feat: 피드 수정 기능 추가 + @

---

Client/src/api/error.ts
Client/src/api/user.ts
Client/src/components/main/CheckInScreen.tsx
Client/src/hooks/useCheckInQuery.tsx
Client/src/pages/MainPage.tsx

출석-체크
메인 페이지 접근 시 자동으로 출석 여부를 확인한 후 출석을 하지 않았다면 출석 보상 페이지로 이동합니다.
출석한 상태에서 출석 보상 페이지에 접근하면 메인 페이지로 이동합니다.
출석 여부 확인 쿼리는 `staleTime`, `cacheTime`을 무한으로 설정했습니다.

✨ feat: 출석 체크 기능

---

Client/src/api/myFeedList.ts
Client/src/api/userFeed.ts
Client/src/components/main/ProfileScreen.tsx
Client/src/hooks/useUserFeedListQuery.tsx

- 메이페이지에서 사용자가 업로드한 피드 내역 렌더링 추가 (api, hook) 
- 무한스크롤 추가

✨feat : 마이페이지, 나의 피드 리스트 

---

Client/src/components/feed-detail/FeedDetailModal.tsx
Client/src/components/feed/FeedItem.tsx
Client/src/components/feed/FeedList.tsx
Client/src/components/feed/Header.tsx
Client/src/components/feed/SearchResult.tsx
Client/src/components/main/ProfileScreen.tsx
Client/src/components/main/StatusScreen.tsx
Client/src/pages/FeedPage.tsx
Client/src/pages/SearchPage.tsx

https://github.com/codestates-seb/seb45_main_022/assets/85780501/3923ed1e-1c5c-4461-b7d7-d78dfeabcdae
<br>
- 추가로 기존 컴포넌트 재사용으로 인해, 라우트가 꼬이는 현상이 아직 있는데 추후에 픽스할 예정입니다.

✨ feat: Header에 로그인한 개인 유저 정보를 연동 & 클릭 시, 모달창 노출하는 기능 추가

---

Client/src/api/feed.ts
Client/src/api/like.ts
Client/src/components/feed-detail/FeedContentSection.tsx
Client/src/components/feed/FeedItem.tsx
Client/src/hooks/useLikeMutation.tsx

https://github.com/codestates-seb/seb45_main_022/assets/85780501/154c56f7-0ed3-4df8-9150-4efa66e5710f
<br>
- 피드 상세 페이지와 피드 페이지의 좋아요 기능 연동이 완료되었습니다 !

✨ feat: Feed 상세 페이지에 좋아요 기능 추가 & 좋아요 로직 `Api`와 `Hook`으로 분리 리팩토링

---

Client/src/components/main/StatusChart.tsx

💄 design: 스테이터스 차트 모양 설정 수정

---

Client/src/components/feed/FeedItem.tsx
Client/src/components/main/StatusChart.tsx
Client/src/index.css

스크롤 바 커스터마이징 했습니다
태그 스크롤 저 정도면... 괜찮지 않나? 싶은데 ㅎㅎ...
의견 적극 수용하겠습니다.

💄 design: 스크롤 바 커스텀

---

Client/src/api/comment.ts
Client/src/api/feed.ts
Client/src/components/feed-detail/CommentItem.tsx
Client/src/components/feed-detail/CommentSection.tsx
Client/src/hooks/useCommentListQuery.tsx
Client/src/hooks/usePostCommentMutation.tsx

✨ feat: 코멘트 API 변경에 따른 코드 수정 및 무한 스크롤 적용

---

Server/src/main/java/com/codestatus/domain/user/controller/UserController.java
Server/src/main/java/com/codestatus/domain/user/dto/UserDto.java
Server/src/main/java/com/codestatus/domain/user/mapper/UserMapper.java
Server/src/main/java/com/codestatus/global/auth/config/SecurityConfig.java

- 다른 유저의 정보를 조회하는 api 추가 했습니다.
- 조회 테스트 및 예외 처리 확인 완료

✨ feat: 다른 유저 정보조회 api 추가

---

Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
Server/src/main/java/com/codestatus/domain/feed/service/FeedService.java
Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
Server/src/main/java/com/codestatus/domain/hashTag/repository/HashTagRepository.java

✨ feat: userId로 피드 조회 api추가, 🐛 fix: 해시태그 검색 시 포함 아닌 일치로

---

Client/src/api/error.ts
Client/src/hooks/useUserInfoQuery.tsx
Client/src/main.tsx
Client/src/pages/AuthPage.tsx
Client/src/pages/TitlePage.tsx

♻️ refactor: 토스트 표시 여부 선택 + 에러 코드 및 에러 메시지 추가

---

Client/src/api/feed.ts
Client/src/components/feed-detail/UserInfoSection.tsx
Client/src/components/feed/FeedItem.tsx
Client/src/components/main/OtherUserFeedsTab.tsx
Client/src/components/main/OtherUserProfileHeader.tsx
Client/src/components/main/OtherUserProfileScreen.tsx
Client/src/hooks/useOtherUserInfoQuery.tsx
Client/src/main.tsx

https://github.com/codestates-seb/seb45_main_022/assets/85780501/f346e2db-65bc-4490-80ce-9745c444e141
<br>
- 현재 특정 유저의 전체 글을 조회할 수 있는 API가 없어, 한 개의 해당 카테고리에서만 작성한 글을 조회할 수 있습니다.
- 현재는 피드 페이지의 1페이지에서 작성된 글 정보만 가져올 수 있는데, 이 부분은 추후에 무한 스크롤과 함께 기능 추가할 예정입니다.

✨ feat: 피드 & 피드 상세 페이지에서 특정 유저 프로필을 볼 수 있는 기능 추가
