codestates-seb/seb45_main_022

Server/src/main/java/com/codestatus/domain/status/entity/Status.java
Server/src/main/java/com/codestatus/domain/user/dto/StatusResponse.java
Server/src/main/java/com/codestatus/domain/user/mapper/UserMapper.java
Server/src/main/java/com/codestatus/domain/user/service/UserService.java
Server/src/main/java/com/codestatus/global/utils/ExpTableGenerator.java

- status 테이블에 required_exp 컬럼 추가
- UserService 클래스 내부 levelUpCheck() 메서드에 다음 레벨까지 필요 경험치 계산 코드 추가
- StatusResponse, UserMapper 에 requiredExp 추가

🐛 fix: myPage 조회시 각 스탯의 레벨업까지 남은 경험치 추가

---

Server/src/main/java/com/codestatus/domain/category/dto/CategoryResponseDto.java
Server/src/main/java/com/codestatus/domain/status/controller/StatController.java
Server/src/main/java/com/codestatus/domain/status/dto/StatResponseDto.java
Server/src/main/java/com/codestatus/domain/status/entity/Stat.java
Server/src/main/java/com/codestatus/domain/status/mapper/StatMapper.java
Server/src/main/java/com/codestatus/domain/status/service/StatService.java
Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java

✨  feat:get categories with stat id  API 추가
- stat id로 해당 스탯과 관련한 카테고리 리스트를 보여주는 api를 추가하였습니다.
- stat id가 1이상 5이하의 stat만 조회가 가능합니다.
Test Case
- 로컬에서 postman으로 request 확인하였습니다.
- 1이상 5이하의 stat id만 조회 가능한지 확인하였습니다.

✨  feat:get categories with stat id  API 추가

---

Server/src/main/java/com/codestatus/domain/like/service/LikeService.java
Server/src/main/java/com/codestatus/domain/user/controller/UserController.java
Server/src/main/java/com/codestatus/domain/user/service/LevelService.java
Server/src/main/java/com/codestatus/domain/user/service/UserService.java

♻ refactor: user service에서 level service 분리
- user service에서 레벨 관련 기능을 분리해서 level service를 추가하였습니다.
- user service에서 회원가입 할 때 stat별 status를 생성하는 로직을 줄였습니다.
- user controller에서 @AuthenticationPrincipal을 통해 principal을 service에 전달하여 사용하도록 하였습니다.
Test Case
- postman을 통해 회원가입, 로그인, 피드 좋아요 기능 확인하였습니다.

♻ refactor: user service에서 level service 분리

---

Client/src/api/auth.ts
Client/src/api/user.ts
Client/src/components/title/ProfileScreen.tsx
Client/src/components/title/StatusChart.tsx
Client/src/components/title/StatusListItem.tsx
Client/src/components/title/StatusScreen.tsx
Client/src/hooks/useUserInfo.tsx
Client/src/pages/TitlePage.tsx

https://github.com/codestates-seb/seb45_main_022/blob/ce8d5a2f475f96d53d63df558293025b8ce80354/Client/src/api/user.ts#L19-L22
`ProfileScreen`, `StatusScreen` 컴포넌트 내에서 유저 정보 조회 API 요청하던 코드 따로 분리
<br />
https://github.com/codestates-seb/seb45_main_022/blob/ce8d5a2f475f96d53d63df558293025b8ce80354/Client/src/hooks/useUserInfo.tsx#L4-L10
**React query**를 사용해 유저 정보를 관리하는  `useUserInfo`  커스텀 훅 작성
<br />
https://github.com/codestates-seb/seb45_main_022/blob/ce8d5a2f475f96d53d63df558293025b8ce80354/Client/src/components/title/ProfileScreen.tsx#L13-L22
https://github.com/codestates-seb/seb45_main_022/blob/ce8d5a2f475f96d53d63df558293025b8ce80354/Client/src/components/title/StatusScreen.tsx#L12-L22
`ProfileScreen`, `StatusScreen` 컴포넌트에서 `useUserInfo`를 사용해 데이터 페칭

♻️ refactor: 유저 정보 조회 커스텀 훅

---

Server/src/main/java/com/codestatus/domain/user/dto/StatusResponse.java
Server/src/main/java/com/codestatus/domain/user/mapper/UserMapper.java

- 유저 정보 조회시 response에 포함된 statuses 의 statName 을 statId 로 응답하게 변경

🐛 fix: 유저 정보 조회 response 일부 변경

---

Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java
Server/src/main/java/com/codestatus/global/mail/service/EmailService.java
Server/src/main/java/com/codestatus/global/report/controller/ReportController.java
Server/src/main/java/com/codestatus/global/report/entity/ReportFeed.java
Server/src/main/java/com/codestatus/global/report/reporitory/ReportFeedRepository.java
Server/src/main/java/com/codestatus/global/report/service/ReportFeedServiceImpl.java
Server/src/main/java/com/codestatus/global/report/service/ReportService.java
Server/src/main/java/com/codestatus/global/utils/CustomMailSender.java
Server/src/main/resources/application-server.yml

✨ feat: feed report api 추가
- feed를 신고할 수 있는 기능을 추가하였습니다.
- 각 피드 별로 사람 당 한 번만 신고가 가능하고 N회 누적 신고 시 관리자에게 이메일을 보냅니다.
✨ feat: email sender 추가
- 회원 가입 시 사용하는 email sender와 신고 누적 시 사용하는 email sender의 공통 기능을 추상화 하였습니다.

✨ feat:feed report api 추가, email sender 추가

---

Client/public/user/test.json
Client/src/api/user.ts
Client/src/components/feed/Header.tsx
Client/src/components/map/ServerList.tsx
Client/src/components/title/StatusChart.tsx
Client/src/components/title/StatusListItem.tsx
Client/src/components/title/StatusScreen.tsx
Client/src/utility/category.ts
Client/src/utility/status.ts

API 응답 데이터에서는 코드 값만 받아 그 코드에 해당하는 이름, 아이콘 등의 정보는 프론트에서 매핑해서 쓸 수 있도록 작성했습니다.  
https://github.com/codestates-seb/seb45_main_022/blob/b15981aa4c4189e7f4c36b41dd203d475452b16e/Client/src/utility/status.ts#L16-L38
https://github.com/codestates-seb/seb45_main_022/blob/b15981aa4c4189e7f4c36b41dd203d475452b16e/Client/src/utility/category.ts#L32-L62
`uitility/icons.ts` 파일을 삭제하고 `utility/status.ts`와 `utility/category.ts` 생성했습니다.
스테이터스 코드, 카테고리 코드 값을 통해 아이콘을 가져올 수 있었던 것에 더해,
스테이터스/카테고리 이름, 스테이터스와 카테고리의 매핑 정보도 가져올 수 있도록 매핑 오브젝트를 작성했습니다.

♻️ refactor: 스테이터스 코드, 카테고리 코드 값을 통해 스테이터스, 카테고리 정보를 가져올 수 있도록 수정

---

Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java

🐛fix:delete hashtag in feed when user resign
- 유저 탈퇴 시 feed, feed hash tag, comment의 deleted를 true로 변경

🐛fix:delete hashtag in feed when user resign

---

Server/src/main/java/com/codestatus/domain/attendance/controller/AttendanceController.java
Server/src/main/java/com/codestatus/domain/attendance/dto/AttendanceDto.java
Server/src/main/java/com/codestatus/domain/attendance/entity/Attendance.java
Server/src/main/java/com/codestatus/domain/attendance/mapper/AttendanceMapper.java
Server/src/main/java/com/codestatus/domain/attendance/repository/AttendanceRepository.java
Server/src/main/java/com/codestatus/domain/attendance/service/AttendanceService.java
Server/src/main/java/com/codestatus/domain/user/controller/UserController.java
Server/src/main/java/com/codestatus/domain/user/service/LevelServiceImpl.java

- UserService 가 가지고 있던 출석체크 기능을 분리해 별도의 service 생성
- attendance 테이블을 추가(userId = unique)
- 출석체크 api 호출시 user Id 를 attendance  테이블에 insert 를 시도하고 이때 userId 가 이미 존재한다면 예외처리
- 스케쥴링으로 매일 자정마다 attendance 테이블의 데이터 일괄 삭제(deleteAll())
- 스탯별 경험치 상승 및 레벨 상승 테스트 완료
- 2회 호출시 예외 발생 확인

♻️ refactor: 일일 출석체크 기능 분리

---

Client/src/components/common/BackButton.tsx
Client/src/components/feed/Header.tsx
Client/src/pages/FeedPage.tsx
Client/src/pages/MapPage.tsx

https://github.com/codestates-seb/seb45_main_022/assets/85780501/5c04ce6b-5e8d-424b-a2c1-9255b5c9738d
<br>
- Map 페이지에서 적용하던 뒤로 가기 버튼을 컴포넌트로 캡슐화하였습니다.
- 추가로 앞으로 가기 버튼도 추가하여, 페이지 간 이동을 원활하게 하였습니다.
- Map 페이지에서 뒤로 가기 버튼을 클릭 시, Main Status 페이지로 이동하게 변경하였습니다.
- Feed 페이지에서 뒤로 가기 & 앞으로 가기 버튼 클릭 시, 카테고리 페이지끼리 이동하도록 하였습니다.

✨ feat: 뒤로 가기 버튼 컴포넌트로 캡슐화 및 Map & Feed 페이지에 적용

---

Server/src/main/java/com/codestatus/domain/comment/command/CommentCommand.java
Server/src/main/java/com/codestatus/domain/comment/repository/CommentRepository.java
Server/src/main/java/com/codestatus/domain/feed/command/FeedCommand.java
Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java

✨ feat: 카테고리 내 특정 키워드의 해쉬태그를 포함한 feed 검색 api 추가
- 검색 테스트 완료
- 삭제된 feed 제외 확인
🐛 fix: feed 검색 uri 수정
- feed 검색용 uri 통일감 있게 수정했습니다.
- /feed/find = 피드 본문 검색(카테고리 구분 없음)
- /feed/find/body/{categoryId} = 카테고리 내 본문으로 피드 검색
- /feed/find/user/{categoryId} = 카테고리 내 작성자로 피드 검색
- /feed/find/hashTag/{categoryId} = 카테고리 내 해쉬태그로 피드 검색
- /feed/find/hashTagId/{categoryId} = 카테고리 내 해쉬태그 id 로 피드 검색
- 변경한 uri 로 동작 확인 완료 했습니다.

✨ feat: 카테고리 내 특정 키워드의 해쉬태그를 포함한 feed 검색 api 추가

---

Server/src/main/java/com/codestatus/global/auth/filter/JwtVerificationFilter.java
Server/src/main/java/com/codestatus/global/auth/handler/UserAuthenticationEntryPoint.java

🐛 fix: add jwtException when refresh token doesn't exist
- access token이 만료된 상황에서 refresh token이 존재하지 않을 때 발생했던 500에러를 해결했습니다.
- 해당 상황일 때 status code 401이고 message는 RefreshToken doesn't exists 라고 반환합니다.
Test Case:
- postman을 사용해 만료된 access token만 넣고 feed 작성 api를 호출하여 예상한 에러 메세지가 response로 나왔습니다.

🐛 fix: add jwtException when refresh token doesn't exist

---

Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
Server/src/main/java/com/codestatus/domain/feed/dto/FeedResponseDto.java
Server/src/main/java/com/codestatus/domain/feed/dto/FeedsResponseDto.java
Server/src/main/java/com/codestatus/domain/feed/mapper/FeedMapper.java
Server/src/main/java/com/codestatus/domain/feed/repository/FeedRepository.java
Server/src/main/java/com/codestatus/domain/feed/service/FeedServiceImpl.java
Server/src/main/java/com/codestatus/domain/like/likeCommand/LikeCommand.java
Server/src/main/java/com/codestatus/domain/like/repository/LikeRepository.java

✨ feat: 피드 상세 조회, 피드 리스트 조회 하면 해당 유저가 피드 좋아요 했는지 표시
- ResponseDto, ResponseDtos에 isLike 추가.
- 모든 피드 조회할때 추가
- MyPost는 본인 글에 좋아요 표시를 못하기 때문에 필요없지만 같은 Dto를 사용해서 넣어주었습니다.
추가) 연성님 피드백 반영했습니다!
♻️ refactor: 피드 좋아요 확인하는 기능 리팩토링. 기존 userId로만 했는데 feeds도 활용하게 해서 DB부하 줄임
✨ feat: 로그인 안했다면 좋아요 누른 피드조회하지 않음.
추가2) 연성님의 피드백 듣고 더 효율적인 쿼리 짜보았습니다.
♻️ refactor: 기존에 likes전체를 조회해서 가져왔는데 이제 feeds에서 범위를 좁히고 likes를 조회합니다.
추가3) 연성님 피드백을 듣고 IN :Feeds위치를 앞으로 당겼습니다.

✨ feat: 좋아요 여부 표시 기능 추가

---

Server/src/main/java/com/codestatus/domain/comment/dto/CommentPostDto.java
Server/src/main/java/com/codestatus/domain/comment/dto/CommnetPatchDto.java
Server/src/main/java/com/codestatus/domain/feed/controller/FeedController.java
Server/src/main/java/com/codestatus/domain/feed/dto/FeedPatchDto.java
Server/src/main/java/com/codestatus/domain/feed/dto/FeedPostDto.java

- feed 본문 및 comment 글자수 제한 추가 했습니다.
- feed 의 body 1024 자 제한
- comment 의 body 255 자 제한
- 작성 및 예외처리 테스트 완료 했습니다.

🐛 fix: feed 본문 및 comment 글자수 제한 추가

---

Server/src/main/java/com/codestatus/global/auth/filter/JwtVerificationFilter.java
Server/src/main/java/com/codestatus/global/auth/handler/UserAuthenticationEntryPoint.java
Server/src/main/java/com/codestatus/global/auth/utils/ErrorResponseSender.java
Server/src/main/java/com/codestatus/global/auth/utils/JwtResponseUtil.java
Server/src/main/java/com/codestatus/global/exception/AccessTokenExpiredException.java
Server/src/main/java/com/codestatus/global/exception/RefreshTokenExpiredException.java
Server/src/main/java/com/codestatus/global/response/ErrorResponse.java
Server/src/main/java/com/codestatus/global/response/JwtErrorResponse.java

🐛 fix: access token 재발급 수정
- refresh token은 유효한 상태에서 access token을 재발급 받을 때, nullpointerror가 뜨는 것을 수정하였습니다.
- 재발급한 access token을 보내기 위한 error response를 추가하였습니다.
✨ feat: jwt 인증 오류 error response 세분화
- jwt 인증 오류 시 발생하는 오류들에 대해 조금 더 세분화 하였습니다.
Test Case:
postman 사용하여 token 위변조 오류, 기한 만료 오류, access token 재발급이 잘 되는지 확인하였습니다.

🐛 fix: access token 재발급 수정, ✨ feat: jwt 인증 오류 error response 세분화

---

Server/src/main/java/com/codestatus/global/auth/handler/OAuth2UserSuccessHandler.java
Server/src/main/resources/application.yml

✨ feat: add kakao oauth2 login
- Oauth2SuccessHandler에 카카오 oauth2 로그인 과정을 추가하였습니다.
- .yml에 카카오 oauth2 로그인을 위한 설정을 추가하였습니다.
Test Case:
- 로컬 환경에서 chrome client로 kako 로그인 성공 했습니다.
PS:
- front에서 로그인, 회원가입 페이지 url을 받아 
Oauth2SuceessHandler에서 redirect url을 바꿔야 합니다.

✨ feat: add kakao oauth2 login

---

Server/src/main/java/com/codestatus/global/auth/userdetails/UsersDetailService.java

🐛 fix: get user status on custom user details
- 로그인 시 active 상태가 아닌 유저들의 로그인이 되던 문제를 해결했습니다.

🐛 fix: get user status on custom user details

---

Server/src/main/java/com/codestatus/domain/status/command/StatusCommand.java
Server/src/main/java/com/codestatus/domain/status/repository/StatusRepository.java
Server/src/main/java/com/codestatus/domain/user/entity/User.java
Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java

🐛 fix: user 탈퇴시 status 정보 초기화 및 status 생성 메서드 StatusCommand 클래스로 이동
- StatusCommnad 클래스 생성
- UserServiceImpl 에 있던 createStatus() 를 StatusCommand 로 이동
- status 를 초기화하는 resetStatus() 추가
- user 탈퇴시 해당 user 가 가진 status 정보를 초기화
🐛 fix: 탈퇴한 user 가 재가입 요청시 처리하는 메서드 추가
1. 가입 요청이 온 email 로 user table 검색
2. email 이 존재하는 경우 재가입 메서드 실행
3. email 이 존재하지 않으면 새로운 유저 생성 메서드 실행
Test Case
1. 유저 탈퇴시 status 초기화 확인 완료
2. 새로운 유저 생성 확인 완료
3. DELETE 상태 유저가 재가입 하려는 경우
ㄴ 유저 상태 변경 확인 완료(DELETE -> ACTIVE)
ㄴ 기존과 다른 닉네임을 입력한 경우 닉네임 중복검사 후 저장 확인 완료
ㄴ 기존과 같은 닉네임을 입력한 경우 기존 닉네임 사용 확인 완료
ㄴ 비밀번호는 새로 입력한 비밀번호를 암호화해서 저장 및 로그인 확인 완료

🐛 fix: 재가입 user 처리

---

Server/src/main/java/com/codestatus/domain/user/controller/UserController.java
Server/src/main/java/com/codestatus/domain/user/service/UserService.java
Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java
Server/src/main/java/com/codestatus/global/aws/FileStorageService.java
Server/src/main/java/com/codestatus/global/exception/ExceptionCode.java

✨ feat: 유저 프로필 이미지 초기화 기능 추가
- 유저의 프로필 이미지를 초기화하는 api 추가 했습니다.
- 초기화 요청시 사용중인 프로필 이미지를 s3 에서 삭제하고 기본 프로필 이미지 4개 중 하나로 배정 됩니다.
- 이미 기본 프로필을 사용 하고 있을 경우 예외가 발생합니다.(예외코드 I002 추가)
🐛 fix : 회원 탈퇴시 프로필 이미지 삭제
- 회원 탈퇴 진행시 유저가 업로드한 프로필 이미지 사용 중일때 해당 이미지를 s3 에서 삭제하고 기본 프로필 이미지로 배정 합니다.
- 이미 기본 프로필 이미지를 사용 하고 있을 경우 무시 됩니다.
- 기본 프로필 이미지 url List 중복 사용으로 클래스 내에서 사용 할 수 있게 변경
- 중복되는 로직 메서드로 변경(기본 프로필 이미지 배정 로직)
- rejoinUser() 내부 조건문 로직 변경
Test Case
- 프로필 이미지 초기화 및 s3 파일 삭제 확인 완료
- 기본 프로필 사용으로 인한 예외 발생 확인 완료
- 탈퇴시 업로드 한 프로필 이미지 삭제 및 기본 프로필 이미지로 변경 확인 완료
- 탈퇴시 이미 기본 프로필 이미지 일 경우 무시되는지 확인 완료

✨ feat: 유저 프로필 이미지 초기화 기능 추가

---

Server/src/main/java/com/codestatus/domain/user/dto/UserDto.java
Server/src/main/java/com/codestatus/domain/user/repository/UserRepository.java
Server/src/main/java/com/codestatus/domain/user/service/UserService.java
Server/src/main/java/com/codestatus/domain/user/service/UserServiceImpl.java
Server/src/main/java/com/codestatus/global/auth/config/SecurityConfig.java
Server/src/main/java/com/codestatus/global/auth/handler/OAuth2UserSuccessHandler.java

🐛fix: email validation message
- 회원 가입 시 email validation check message가 잘못 되어있던 것 수정
✨feat: count nickname & ♻️refactor: check nickname
- 닉네임 생성기에서 이메일의 앞부분을 사용하는 유저 수를 가져와
비슷한 닉네임이 있을 시 해당 수 만큼 닉네임 뒤에 더함
- verifiedNickname 메서드에서 jpa의 exists 사용
✨ feat: Oauth User 자동 가입 추가 & 🐛 fix: oauth2 인증 user redirect uri 수정
- Oauth2를 사용한 사용자 인증 시 리소스 서버로 부터 email을 가져와
User 테이블에 존재 시 로그인, 아닐 때 닉네임과 패스워드를 생성해서 
새로운 데이터를 생성한 뒤  uri에 access token과 refresh token을 포함해 redirect
Test Case:
- google, kakao 둘 다 회원 생성 확인하였습니다.

🐛fix: oauth2 인증 외 
